// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdqyj0jLphobQzZe5wiIBc0oKCMdpwqRg',
    appId: '1:262953521889:web:5071614e33682da858dda0',
    messagingSenderId: '262953521889',
    projectId: 'task-management-apps-c9864',
    authDomain: 'task-management-apps-c9864.firebaseapp.com',
    storageBucket: 'task-management-apps-c9864.appspot.com',
    measurementId: 'G-HEBGTDDXWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArQUzXpR3jpeXNkh3hVH_ZY5LgGLrtQc4',
    appId: '1:262953521889:android:1206676ece649f8958dda0',
    messagingSenderId: '262953521889',
    projectId: 'task-management-apps-c9864',
    storageBucket: 'task-management-apps-c9864.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSFMCeA3rDGe17eAYl8dg-mPnePN0j0dY',
    appId: '1:262953521889:ios:b9daead43286b51558dda0',
    messagingSenderId: '262953521889',
    projectId: 'task-management-apps-c9864',
    storageBucket: 'task-management-apps-c9864.appspot.com',
    iosClientId:
        '262953521889-7j0k46k5ikq5gvnel5vlr9tcnabvbq8p.apps.googleusercontent.com',
    iosBundleId: 'com.example.tasManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSFMCeA3rDGe17eAYl8dg-mPnePN0j0dY',
    appId: '1:262953521889:ios:b9daead43286b51558dda0',
    messagingSenderId: '262953521889',
    projectId: 'task-management-apps-c9864',
    storageBucket: 'task-management-apps-c9864.appspot.com',
    iosClientId:
        '262953521889-7j0k46k5ikq5gvnel5vlr9tcnabvbq8p.apps.googleusercontent.com',
    iosBundleId: 'com.example.tasManagementApp',
  );
}
